version: '3'

services:
  db:
    image: mysql
    container_name: mysql_database
    ports:
      - '3306:3306'
    volumes:
      - ./db/data:/var/lib/mysql
    environment:
      MYSQL_DATABASE : homedong
      MYSQL_ROOT_PASSWORD : ${DB_PASSWORD}
    networks:
      - homedong_network
  spring:
    depends_on:
      - db
    restart: always
    container_name: homedong-application
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}

    networks:
      - homedong_network
networks:
  homedong_network:
